### ISSUE TITLE
Yami azonosító egyediség ellenőrzés

### ISSUE THREAD

**Issue by martonkrisztian** [akosk/jezsumenza#120]
Felhasználó rögzítése során szükséges lenne a yami azonosító egyediségének ellenőrzésére. Na most a legutóbbi JSON file alapján mintha arra jutottunk volna, hogy a yami azonosító=kártya azonosító. Neked ez kitisztult?

**Comment by akosk** [comment]
Nem ugyanaz, lásd #122
