### ISSUE TITLE
Konyhafőnök statisztika

### ISSUE THREAD

**Issue by martonkrisztian** [akosk/jezsumenza#121]
A konyhafőnöknek kellene egy statisztika. 
Egy napra, a három menüt hányan választották. Egy db számot kell adnia adott napra, mind a 3 menüre külön. Ezek alapján tudja majd, hogy melyik menüből hány főre kell főznie. 
Az ebéd menüben ugyan ott vannak ezek az adatok, de azt végigkattintgatni neki minden nap a 3 menünél az túl körülményes.
MK: Szerintem egy oldalon megjeleníthető lenne az összes nap a 3 menüvel, darabszámmal, amire menü lett kiírva, persze csak ami még dátum szerint előtte van. A korábbiakat, amelyik nap már elmúlt, az már nem kell.

**Comment by akosk** [comment]
Ez már készen van, az ebéd menük alatt láthatja, hogy hányan választották az adott menüt.
