### ISSUE TITLE
Felhasználók listájában szűrés módosítása

### ISSUE THREAD

**Issue by martonkrisztian** [akosk/jezsumenza#122]
Attila szeretné, hogy a felhasználók kezelésénél (felhasználók listája) tudna keresni a Yami azonosítóra és a kártya azonosítóra is. Nem szükséges megjeleníteni oszlopként ezeket a mezőket, bár az is jó, de nekem elég egy kereső mező.
Két kérdés van ezzel kapcsolatban:
1.) A yami azonosító, akkor most nem egyenlő a kártya azonosítóval? A legutóbbi JSON file alapján, mintha erre jutottunk volna.
2.) Ha nem jelennének meg az adott mezők (vagy mező) a listában, akkor hogyan is működhetne a rájuk történő szűrés?

**Comment by akosk** [comment]
1: nem ugyanaz, a yamisok hívják a json fájlban kártyaazonosítónak a yami id-t, innen a kavar.
2: egyszerűen beteszem a két új oszlopot.
