### ISSUE TITLE
Menü szétosztás nem működik

### ISSUE THREAD

**Issue by martonkrisztian** [akosk/jezsumenza#128]
Első tapasztalatok, hogy sokan nem rendeltek és úgy tűnik a rendszer nem osztott nekik menüt.
"Volt egy olyan rész, hogy azokat a tanulókat, akik nem rendeltek, azokat a rendszer arányosan szétosztja a 3 menü között."

**Comment by akosk** [comment]
#9 során lett implementálva, az időzítés viszont akkor még nem lett beállítva a szerverükön.
Mikorra időzítsem (szerda?) ?
