### ISSUE TITLE
Bejelentkezési probléma

### ISSUE THREAD

**Issue by martonkrisztian** [akosk/jezsumenza#58]
mark userrel (adminisztrátor role) próbáltam belépni, de hibát dobott. Korábban ez működött:

An Error occurred while handling another error:
exception 'yii\web\ForbiddenHttpException' with message 'Nincs jogosultsĂĄga a mĹąvelet vĂŠgrehajtĂĄsĂĄhoz.' in /var/www/jezsumenza/vendor/yiisoft/yii2/filters/AccessControl.php:151
Stack trace:
#0 /var/www/jezsumenza/vendor/yiisoft/yii2/filters/AccessControl.php(134): yii\filters\AccessControl->denyAccess(Object(yii\web\User))
#1 /var/www/jezsumenza/vendor/yiisoft/yii2/base/ActionFilter.php(71): yii\filters\AccessControl->beforeAction(Object(yii\web\ErrorAction))
#2 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#3 /var/www/jezsumenza/vendor/yiisoft/yii2/base/Component.php(541): call_user_func(Array, Object(yii\base\ActionEvent))
#4 /var/www/jezsumenza/vendor/yiisoft/yii2/base/Controller.php(263): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#5 /var/www/jezsumenza/vendor/yiisoft/yii2/web/Controller.php(108): yii\base\Controller->beforeAction(Object(yii\web\ErrorAction))
#6 /var/www/jezsumenza/controllers/ControllerBase.php(23): yii\web\Controller->beforeAction(Object(yii\web\ErrorAction))
#7 /var/www/jezsumenza/vendor/yiisoft/yii2/base/Controller.php(149): app\controllers\ControllerBase->beforeAction(Object(yii\web\ErrorAction))
#8 /var/www/jezsumenza/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('error', Array)
#9 /var/www/jezsumenza/vendor/yiisoft/yii2/web/ErrorHandler.php(80): yii\base\Module->runAction('site/error')
#10 /var/www/jezsumenza/vendor/yiisoft/yii2/base/ErrorHandler.php(101): yii\web\ErrorHandler->renderException(Object(yii\web\ForbiddenHttpException))
#11 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\ForbiddenHttpException))
#12 {main}

Previous exception:
exception 'yii\web\ForbiddenHttpException' with message 'Nincs jogosultsĂĄga a mĹąvelet vĂŠgrehajtĂĄsĂĄhoz.' in /var/www/jezsumenza/vendor/yiisoft/yii2/filters/AccessControl.php:151
Stack trace:
#0 /var/www/jezsumenza/vendor/yiisoft/yii2/filters/AccessControl.php(134): yii\filters\AccessControl->denyAccess(Object(yii\web\User))
#1 /var/www/jezsumenza/vendor/yiisoft/yii2/base/ActionFilter.php(71): yii\filters\AccessControl->beforeAction(Object(yii\base\InlineAction))
#2 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#3 /var/www/jezsumenza/vendor/yiisoft/yii2/base/Component.php(541): call_user_func(Array, Object(yii\base\ActionEvent))
#4 /var/www/jezsumenza/vendor/yiisoft/yii2/base/Controller.php(263): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#5 /var/www/jezsumenza/vendor/yiisoft/yii2/web/Controller.php(108): yii\base\Controller->beforeAction(Object(yii\base\InlineAction))
#6 /var/www/jezsumenza/vendor/yiisoft/yii2/base/Controller.php(149): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#7 /var/www/jezsumenza/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('', Array)
#8 /var/www/jezsumenza/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('user/admin', Array)
#9 /var/www/jezsumenza/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#10 /var/www/jezsumenza/web/index.php(12): yii\base\Application->run()
#11 {main}

**Comment by akosk** [comment]
Arra gondolok, hogy az oldal nem volt bezárva és mivel sok idő eltelt a tényleges loginig, a csrf azonosító lejárt, emiatt tilthatta meg a hozzáférést.

**Comment by akosk** [comment]
Kikapcsoltam a csrf validációt a bejelentkezésnél. Viszont ez "máshol" is probléma lehet... kellene egy szebb error oldal.
