### ISSUE TITLE
Ételek listája formázás

### ISSUE THREAD

**Issue by martonkrisztian** [akosk/jezsumenza#59]
Az ételek listájában én a sorszámot ki se tenném és az azonosító mező szélességét amennyire lehet csökkenteném, mert jelenleg ez a 2 oszlop túl hangsúlyos, míg az étel neve és kategóriája nem feltűnő. Szóval az étel neve és a kategória kellene, hogy hangsúlyos legyen.

**Comment by akosk** [comment]
A sorszám mezőnek szerintem a lapozásnál van jelentősége, jobban áttekinthetővé teszi, hogy hol jár. Kivegyük mindenhonnan?
